describe('AI Generated Tests - Automation Exercise', () => {
  
  beforeEach(() => {
    cy.visit('https://automationexercise.com');
  });

  it('should validate the subscription email input with invalid format', () => {
    // AI generated scenario: Testing boundary/invalid values for email subscription in the footer
    const invalidEmailFormat = 'ai_test_user_without_at.com';
    const subscribeInputSelector = '#susbscribe_email';
    const subscribeButtonSelector = '#subscribe';

    // Scroll to the footer and type the invalid email
    cy.get(subscribeInputSelector).scrollIntoView().type(invalidEmailFormat);
    cy.get(subscribeButtonSelector).click();

    // Verify the input still contains the text (meaning form wasn't cleared/submitted successfully)
    cy.get(subscribeInputSelector).should('have.value', invalidEmailFormat);
  });

  it('should successfully fill out the contact us form', () => {
    // AI generated scenario: Automated form filling and submission validation
    const userName = 'AI Test User';
    const userEmail = 'ai_test_user@example.com';
    const userSubject = 'Generated by AI Script';
    const userMessage = 'This is an automated test generated by Artificial Intelligence for CI Pipeline.';

    // Navigate to contact page
    cy.get('a[href="/contact_us"]').click();
    
    // Fill the form
    cy.get('[data-qa="name"]').type(userName);
    cy.get('[data-qa="email"]').type(userEmail);
    cy.get('[data-qa="subject"]').type(userSubject);
    cy.get('[data-qa="message"]').type(userMessage);

    // Submit and verify success message
    cy.get('[data-qa="submit-button"]').click();
    cy.get('.status').should('contain', 'Success! Your details have been submitted successfully.');
  });

});
